### ISSUE TITLE
Docker Container does not come up

### ISSUE THREAD

**Issue by MarcoGriep88** [schn4ck/schnack#137]
Hi there,

just wanted to try out Schnack. I cloned the current repo and created a config file with the following content:

`
{
    "schnack_host": "http://localhost",
    "page_url": "http://localhost/posts/%SLUG%",
    "port": 3000,
    "database": {
        "comments": "comments.db",
        "sessions": "sessions.db"
    },
    "admins": [1],
    "plugins": {
        "notify-sendmail": {
            "to": "admin@blog.example.com",
            "from": "schnack@blog.example.com"
        }
    },
    "oauth": {
        "secret": "secret"
    },
    "date_format": "MMMM DD, YYYY - h:mm a"
}
`

After build the container does not come up successfully. Using Windows 10 and Docker with WSL2. Did not try to run this on my Linux machine yet.

`
 docker logs 9caf41ac97f6b134cbb80f99ad0cea34ddb3c0b092b9336e496f774b61008b5c

> schnack@1.2.0 server /usr/src/app
> NODE_ENV=development nodemon index.js

/usr/src/app/node_modules/chokidar/index.js:161
  async remove(item) {
        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/node_modules/nodemon/lib/monitor/watch.js:6:16)

npm ERR! Linux 5.4.72-microsoft-standard-WSL2
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "server"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! schnack@1.2.0 server: `NODE_ENV=development nodemon index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the schnack@1.2.0 server script 'NODE_ENV=development nodemon index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the schnack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development nodemon index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs schnack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls schnack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
`

**Comment by RealOrangeOne** [comment]
Node 6 is incredibly old, and no longer supported. I think the container needs updating from `boron` (6.x). After that, it should work. Editing the `Dockerfile` and changing "boron" to "lts" should work, assuming it's not depending elsewhere on older versions.
